# Generated by Django 5.0 on 2023-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblePoints',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longtitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assemble_points',
                'db_table_comment': 'Пункт сбора',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('surname', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GooseDbVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.BigIntegerField()),
                ('is_applied', models.BooleanField()),
                ('tstamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goose_db_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedProductsFromWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordered_products_from_warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'db_table_comment': 'Список товаров',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsInAssemblePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('assemble_point_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_in_assemble_point',
                'managed': False,
            },
        ),
    ]
